Feature/add-address-entity
FAP2024-Turma02/vmaxnet-api pull request #15
Opened 2024-10-08 05:04 UTC by AlansidneyJunior

Não sei as rotas estão funcionando perfeitamente.

2024-10-09 04:06 UTC, AlansidneyJunior commented
Descobri o problema com as rotas index e show de Address. Mas não sei como corrigir nesse PR. Devo criar outro?

2024-10-09 14:14 UTC, pablomorato1 requested changes

2024-10-09 14:14 UTC, pablomorato1 commented on db/schema.rb
> +  create_table "clients", force: :cascade do |t|
Se o PR é só pra Address, o que faz a tabela de client aqui no schema?

2024-10-22 02:16 UTC, pablomorato1 approved these changes
🥳

2024-10-24 12:38 UTC, merged